baseURL = "/"
title = "isadora"
theme = "risotto"
copyright = "🍌 2024"
paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]

# Automatically add content sections to main menu
sectionPagesMenu = "main"

[params]
noindex = false

[params.theme]
palette = "bubblegum"

# Sidebar: about/bio
[params.about]
description = "![](/images/html/me.png)"

# Sidebar: social links
# Available icon sets:
# * FontAwesome 6 <https://fontawesome.com/> ('fa-brands', 'fa-normal', or 'fa-solid' for brands)
# * Academicons <https://jpswalsh.github.io/academicons> ('ai ai-')

[[params.socialLinks]]
img = "/images/html/mastodon.png"
imgHover = "/images/html/hovered.png"
title = "mastodon"
url = "https://mastodon.gamedev.place/@isadora"

[[params.socialLinks]]
img = "/images/html/email.png"
imgHover = "/images/html/hovered.png"
title = "email"
url = "mailto:isadorasophiagr@gmail.com"

[[params.socialLinks]]
img = "/images/html/github.png"
imgHover = "/images/html/hovered.png"
title = "github"
url = "https://github.com/isadorasophia"

[[params.socialLinks]]
img = "/images/html/linkedin.png"
imgHover = "/images/html/hovered.png"
title = "linkedin"
url = "https://www.linkedin.com/in/isadora-sophia-rodopoulos-488726107/"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

# For hugo >= 0.60.0, enable inline HTML
[markup.goldmark.renderer]
unsafe = true

[privacy]
  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]
  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true

[markup.highlight]
  noClasses = false
